// AUTO-GENERATED by scripts/build-data.mjs — DO NOT EDIT BY HAND.
// Source: github.com/openfootball/worldcup (2026--usa), retrieved 2026-06-12.
// Re-run: node scripts/build-data.mjs
import type { Team, Group, Match } from '../types';

export const teams: Team[] = [
  {
    "id": "mexico",
    "name": "Mexico",
    "countryCode": "mx",
    "flag": "🇲🇽",
    "groupId": "A"
  },
  {
    "id": "south-africa",
    "name": "South Africa",
    "countryCode": "za",
    "flag": "🇿🇦",
    "groupId": "A"
  },
  {
    "id": "south-korea",
    "name": "South Korea",
    "countryCode": "kr",
    "flag": "🇰🇷",
    "groupId": "A"
  },
  {
    "id": "czech-republic",
    "name": "Czech Republic",
    "countryCode": "cz",
    "flag": "🇨🇿",
    "groupId": "A"
  },
  {
    "id": "canada",
    "name": "Canada",
    "countryCode": "ca",
    "flag": "🇨🇦",
    "groupId": "B"
  },
  {
    "id": "bosnia-herzegovina",
    "name": "Bosnia & Herzegovina",
    "countryCode": "ba",
    "flag": "🇧🇦",
    "groupId": "B"
  },
  {
    "id": "qatar",
    "name": "Qatar",
    "countryCode": "qa",
    "flag": "🇶🇦",
    "groupId": "B"
  },
  {
    "id": "switzerland",
    "name": "Switzerland",
    "countryCode": "ch",
    "flag": "🇨🇭",
    "groupId": "B"
  },
  {
    "id": "brazil",
    "name": "Brazil",
    "countryCode": "br",
    "flag": "🇧🇷",
    "groupId": "C"
  },
  {
    "id": "morocco",
    "name": "Morocco",
    "countryCode": "ma",
    "flag": "🇲🇦",
    "groupId": "C"
  },
  {
    "id": "haiti",
    "name": "Haiti",
    "countryCode": "ht",
    "flag": "🇭🇹",
    "groupId": "C"
  },
  {
    "id": "scotland",
    "name": "Scotland",
    "countryCode": "gb-sct",
    "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "groupId": "C"
  },
  {
    "id": "usa",
    "name": "USA",
    "countryCode": "us",
    "flag": "🇺🇸",
    "groupId": "D"
  },
  {
    "id": "paraguay",
    "name": "Paraguay",
    "countryCode": "py",
    "flag": "🇵🇾",
    "groupId": "D"
  },
  {
    "id": "australia",
    "name": "Australia",
    "countryCode": "au",
    "flag": "🇦🇺",
    "groupId": "D"
  },
  {
    "id": "turkey",
    "name": "Turkey",
    "countryCode": "tr",
    "flag": "🇹🇷",
    "groupId": "D"
  },
  {
    "id": "germany",
    "name": "Germany",
    "countryCode": "de",
    "flag": "🇩🇪",
    "groupId": "E"
  },
  {
    "id": "curacao",
    "name": "Curaçao",
    "countryCode": "cw",
    "flag": "🇨🇼",
    "groupId": "E"
  },
  {
    "id": "ivory-coast",
    "name": "Ivory Coast",
    "countryCode": "ci",
    "flag": "🇨🇮",
    "groupId": "E"
  },
  {
    "id": "ecuador",
    "name": "Ecuador",
    "countryCode": "ec",
    "flag": "🇪🇨",
    "groupId": "E"
  },
  {
    "id": "netherlands",
    "name": "Netherlands",
    "countryCode": "nl",
    "flag": "🇳🇱",
    "groupId": "F"
  },
  {
    "id": "japan",
    "name": "Japan",
    "countryCode": "jp",
    "flag": "🇯🇵",
    "groupId": "F"
  },
  {
    "id": "sweden",
    "name": "Sweden",
    "countryCode": "se",
    "flag": "🇸🇪",
    "groupId": "F"
  },
  {
    "id": "tunisia",
    "name": "Tunisia",
    "countryCode": "tn",
    "flag": "🇹🇳",
    "groupId": "F"
  },
  {
    "id": "belgium",
    "name": "Belgium",
    "countryCode": "be",
    "flag": "🇧🇪",
    "groupId": "G"
  },
  {
    "id": "egypt",
    "name": "Egypt",
    "countryCode": "eg",
    "flag": "🇪🇬",
    "groupId": "G"
  },
  {
    "id": "iran",
    "name": "Iran",
    "countryCode": "ir",
    "flag": "🇮🇷",
    "groupId": "G"
  },
  {
    "id": "new-zealand",
    "name": "New Zealand",
    "countryCode": "nz",
    "flag": "🇳🇿",
    "groupId": "G"
  },
  {
    "id": "spain",
    "name": "Spain",
    "countryCode": "es",
    "flag": "🇪🇸",
    "groupId": "H"
  },
  {
    "id": "cape-verde",
    "name": "Cape Verde",
    "countryCode": "cv",
    "flag": "🇨🇻",
    "groupId": "H"
  },
  {
    "id": "saudi-arabia",
    "name": "Saudi Arabia",
    "countryCode": "sa",
    "flag": "🇸🇦",
    "groupId": "H"
  },
  {
    "id": "uruguay",
    "name": "Uruguay",
    "countryCode": "uy",
    "flag": "🇺🇾",
    "groupId": "H"
  },
  {
    "id": "france",
    "name": "France",
    "countryCode": "fr",
    "flag": "🇫🇷",
    "groupId": "I"
  },
  {
    "id": "senegal",
    "name": "Senegal",
    "countryCode": "sn",
    "flag": "🇸🇳",
    "groupId": "I"
  },
  {
    "id": "iraq",
    "name": "Iraq",
    "countryCode": "iq",
    "flag": "🇮🇶",
    "groupId": "I"
  },
  {
    "id": "norway",
    "name": "Norway",
    "countryCode": "no",
    "flag": "🇳🇴",
    "groupId": "I"
  },
  {
    "id": "argentina",
    "name": "Argentina",
    "countryCode": "ar",
    "flag": "🇦🇷",
    "groupId": "J"
  },
  {
    "id": "algeria",
    "name": "Algeria",
    "countryCode": "dz",
    "flag": "🇩🇿",
    "groupId": "J"
  },
  {
    "id": "austria",
    "name": "Austria",
    "countryCode": "at",
    "flag": "🇦🇹",
    "groupId": "J"
  },
  {
    "id": "jordan",
    "name": "Jordan",
    "countryCode": "jo",
    "flag": "🇯🇴",
    "groupId": "J"
  },
  {
    "id": "portugal",
    "name": "Portugal",
    "countryCode": "pt",
    "flag": "🇵🇹",
    "groupId": "K"
  },
  {
    "id": "dr-congo",
    "name": "DR Congo",
    "countryCode": "cd",
    "flag": "🇨🇩",
    "groupId": "K"
  },
  {
    "id": "uzbekistan",
    "name": "Uzbekistan",
    "countryCode": "uz",
    "flag": "🇺🇿",
    "groupId": "K"
  },
  {
    "id": "colombia",
    "name": "Colombia",
    "countryCode": "co",
    "flag": "🇨🇴",
    "groupId": "K"
  },
  {
    "id": "england",
    "name": "England",
    "countryCode": "gb-eng",
    "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "groupId": "L"
  },
  {
    "id": "croatia",
    "name": "Croatia",
    "countryCode": "hr",
    "flag": "🇭🇷",
    "groupId": "L"
  },
  {
    "id": "ghana",
    "name": "Ghana",
    "countryCode": "gh",
    "flag": "🇬🇭",
    "groupId": "L"
  },
  {
    "id": "panama",
    "name": "Panama",
    "countryCode": "pa",
    "flag": "🇵🇦",
    "groupId": "L"
  }
];

export const groups: Group[] = [
  {
    "id": "A",
    "teamIds": [
      "mexico",
      "south-africa",
      "south-korea",
      "czech-republic"
    ]
  },
  {
    "id": "B",
    "teamIds": [
      "canada",
      "bosnia-herzegovina",
      "qatar",
      "switzerland"
    ]
  },
  {
    "id": "C",
    "teamIds": [
      "brazil",
      "morocco",
      "haiti",
      "scotland"
    ]
  },
  {
    "id": "D",
    "teamIds": [
      "usa",
      "paraguay",
      "australia",
      "turkey"
    ]
  },
  {
    "id": "E",
    "teamIds": [
      "germany",
      "curacao",
      "ivory-coast",
      "ecuador"
    ]
  },
  {
    "id": "F",
    "teamIds": [
      "netherlands",
      "japan",
      "sweden",
      "tunisia"
    ]
  },
  {
    "id": "G",
    "teamIds": [
      "belgium",
      "egypt",
      "iran",
      "new-zealand"
    ]
  },
  {
    "id": "H",
    "teamIds": [
      "spain",
      "cape-verde",
      "saudi-arabia",
      "uruguay"
    ]
  },
  {
    "id": "I",
    "teamIds": [
      "france",
      "senegal",
      "iraq",
      "norway"
    ]
  },
  {
    "id": "J",
    "teamIds": [
      "argentina",
      "algeria",
      "austria",
      "jordan"
    ]
  },
  {
    "id": "K",
    "teamIds": [
      "portugal",
      "dr-congo",
      "uzbekistan",
      "colombia"
    ]
  },
  {
    "id": "L",
    "teamIds": [
      "england",
      "croatia",
      "ghana",
      "panama"
    ]
  }
];

export const matches: Match[] = [
  {
    "id": "m001",
    "number": 1,
    "stage": "group",
    "groupId": "A",
    "roundLabel": "Group A",
    "kickoff": "2026-06-11T19:00:00.000Z",
    "venue": "Mexico City",
    "home": {
      "kind": "team",
      "teamId": "mexico"
    },
    "away": {
      "kind": "team",
      "teamId": "south-africa"
    },
    "officialResult": {
      "homeGoals": 2,
      "awayGoals": 0
    }
  },
  {
    "id": "m002",
    "number": 2,
    "stage": "group",
    "groupId": "A",
    "roundLabel": "Group A",
    "kickoff": "2026-06-12T02:00:00.000Z",
    "venue": "Guadalajara (Zapopan)",
    "home": {
      "kind": "team",
      "teamId": "south-korea"
    },
    "away": {
      "kind": "team",
      "teamId": "czech-republic"
    },
    "officialResult": {
      "homeGoals": 2,
      "awayGoals": 1
    }
  },
  {
    "id": "m003",
    "number": 3,
    "stage": "group",
    "groupId": "B",
    "roundLabel": "Group B",
    "kickoff": "2026-06-12T19:00:00.000Z",
    "venue": "Toronto",
    "home": {
      "kind": "team",
      "teamId": "canada"
    },
    "away": {
      "kind": "team",
      "teamId": "bosnia-herzegovina"
    },
    "officialResult": {
      "homeGoals": 1,
      "awayGoals": 1
    }
  },
  {
    "id": "m004",
    "number": 4,
    "stage": "group",
    "groupId": "D",
    "roundLabel": "Group D",
    "kickoff": "2026-06-13T01:00:00.000Z",
    "venue": "Los Angeles (Inglewood)",
    "home": {
      "kind": "team",
      "teamId": "usa"
    },
    "away": {
      "kind": "team",
      "teamId": "paraguay"
    },
    "officialResult": null
  },
  {
    "id": "m005",
    "number": 5,
    "stage": "group",
    "groupId": "B",
    "roundLabel": "Group B",
    "kickoff": "2026-06-13T19:00:00.000Z",
    "venue": "San Francisco Bay Area (Santa Clara)",
    "home": {
      "kind": "team",
      "teamId": "qatar"
    },
    "away": {
      "kind": "team",
      "teamId": "switzerland"
    },
    "officialResult": null
  },
  {
    "id": "m006",
    "number": 6,
    "stage": "group",
    "groupId": "C",
    "roundLabel": "Group C",
    "kickoff": "2026-06-13T22:00:00.000Z",
    "venue": "New York/New Jersey (East Rutherford)",
    "home": {
      "kind": "team",
      "teamId": "brazil"
    },
    "away": {
      "kind": "team",
      "teamId": "morocco"
    },
    "officialResult": null
  },
  {
    "id": "m007",
    "number": 7,
    "stage": "group",
    "groupId": "C",
    "roundLabel": "Group C",
    "kickoff": "2026-06-14T01:00:00.000Z",
    "venue": "Boston (Foxborough)",
    "home": {
      "kind": "team",
      "teamId": "haiti"
    },
    "away": {
      "kind": "team",
      "teamId": "scotland"
    },
    "officialResult": null
  },
  {
    "id": "m008",
    "number": 8,
    "stage": "group",
    "groupId": "D",
    "roundLabel": "Group D",
    "kickoff": "2026-06-14T04:00:00.000Z",
    "venue": "Vancouver",
    "home": {
      "kind": "team",
      "teamId": "australia"
    },
    "away": {
      "kind": "team",
      "teamId": "turkey"
    },
    "officialResult": null
  },
  {
    "id": "m009",
    "number": 9,
    "stage": "group",
    "groupId": "E",
    "roundLabel": "Group E",
    "kickoff": "2026-06-14T17:00:00.000Z",
    "venue": "Houston",
    "home": {
      "kind": "team",
      "teamId": "germany"
    },
    "away": {
      "kind": "team",
      "teamId": "curacao"
    },
    "officialResult": null
  },
  {
    "id": "m010",
    "number": 10,
    "stage": "group",
    "groupId": "F",
    "roundLabel": "Group F",
    "kickoff": "2026-06-14T20:00:00.000Z",
    "venue": "Dallas (Arlington)",
    "home": {
      "kind": "team",
      "teamId": "netherlands"
    },
    "away": {
      "kind": "team",
      "teamId": "japan"
    },
    "officialResult": null
  },
  {
    "id": "m011",
    "number": 11,
    "stage": "group",
    "groupId": "E",
    "roundLabel": "Group E",
    "kickoff": "2026-06-14T23:00:00.000Z",
    "venue": "Philadelphia",
    "home": {
      "kind": "team",
      "teamId": "ivory-coast"
    },
    "away": {
      "kind": "team",
      "teamId": "ecuador"
    },
    "officialResult": null
  },
  {
    "id": "m012",
    "number": 12,
    "stage": "group",
    "groupId": "F",
    "roundLabel": "Group F",
    "kickoff": "2026-06-15T02:00:00.000Z",
    "venue": "Monterrey (Guadalupe)",
    "home": {
      "kind": "team",
      "teamId": "sweden"
    },
    "away": {
      "kind": "team",
      "teamId": "tunisia"
    },
    "officialResult": null
  },
  {
    "id": "m013",
    "number": 13,
    "stage": "group",
    "groupId": "H",
    "roundLabel": "Group H",
    "kickoff": "2026-06-15T16:00:00.000Z",
    "venue": "Atlanta",
    "home": {
      "kind": "team",
      "teamId": "spain"
    },
    "away": {
      "kind": "team",
      "teamId": "cape-verde"
    },
    "officialResult": null
  },
  {
    "id": "m014",
    "number": 14,
    "stage": "group",
    "groupId": "G",
    "roundLabel": "Group G",
    "kickoff": "2026-06-15T19:00:00.000Z",
    "venue": "Seattle",
    "home": {
      "kind": "team",
      "teamId": "belgium"
    },
    "away": {
      "kind": "team",
      "teamId": "egypt"
    },
    "officialResult": null
  },
  {
    "id": "m015",
    "number": 15,
    "stage": "group",
    "groupId": "H",
    "roundLabel": "Group H",
    "kickoff": "2026-06-15T22:00:00.000Z",
    "venue": "Miami (Miami Gardens)",
    "home": {
      "kind": "team",
      "teamId": "saudi-arabia"
    },
    "away": {
      "kind": "team",
      "teamId": "uruguay"
    },
    "officialResult": null
  },
  {
    "id": "m016",
    "number": 16,
    "stage": "group",
    "groupId": "G",
    "roundLabel": "Group G",
    "kickoff": "2026-06-16T01:00:00.000Z",
    "venue": "Los Angeles (Inglewood)",
    "home": {
      "kind": "team",
      "teamId": "iran"
    },
    "away": {
      "kind": "team",
      "teamId": "new-zealand"
    },
    "officialResult": null
  },
  {
    "id": "m017",
    "number": 17,
    "stage": "group",
    "groupId": "I",
    "roundLabel": "Group I",
    "kickoff": "2026-06-16T19:00:00.000Z",
    "venue": "New York/New Jersey (East Rutherford)",
    "home": {
      "kind": "team",
      "teamId": "france"
    },
    "away": {
      "kind": "team",
      "teamId": "senegal"
    },
    "officialResult": null
  },
  {
    "id": "m018",
    "number": 18,
    "stage": "group",
    "groupId": "I",
    "roundLabel": "Group I",
    "kickoff": "2026-06-16T22:00:00.000Z",
    "venue": "Boston (Foxborough)",
    "home": {
      "kind": "team",
      "teamId": "iraq"
    },
    "away": {
      "kind": "team",
      "teamId": "norway"
    },
    "officialResult": null
  },
  {
    "id": "m019",
    "number": 19,
    "stage": "group",
    "groupId": "J",
    "roundLabel": "Group J",
    "kickoff": "2026-06-17T01:00:00.000Z",
    "venue": "Kansas City",
    "home": {
      "kind": "team",
      "teamId": "argentina"
    },
    "away": {
      "kind": "team",
      "teamId": "algeria"
    },
    "officialResult": null
  },
  {
    "id": "m020",
    "number": 20,
    "stage": "group",
    "groupId": "J",
    "roundLabel": "Group J",
    "kickoff": "2026-06-17T04:00:00.000Z",
    "venue": "San Francisco Bay Area (Santa Clara)",
    "home": {
      "kind": "team",
      "teamId": "austria"
    },
    "away": {
      "kind": "team",
      "teamId": "jordan"
    },
    "officialResult": null
  },
  {
    "id": "m021",
    "number": 21,
    "stage": "group",
    "groupId": "K",
    "roundLabel": "Group K",
    "kickoff": "2026-06-17T17:00:00.000Z",
    "venue": "Houston",
    "home": {
      "kind": "team",
      "teamId": "portugal"
    },
    "away": {
      "kind": "team",
      "teamId": "dr-congo"
    },
    "officialResult": null
  },
  {
    "id": "m022",
    "number": 22,
    "stage": "group",
    "groupId": "L",
    "roundLabel": "Group L",
    "kickoff": "2026-06-17T20:00:00.000Z",
    "venue": "Dallas (Arlington)",
    "home": {
      "kind": "team",
      "teamId": "england"
    },
    "away": {
      "kind": "team",
      "teamId": "croatia"
    },
    "officialResult": null
  },
  {
    "id": "m023",
    "number": 23,
    "stage": "group",
    "groupId": "L",
    "roundLabel": "Group L",
    "kickoff": "2026-06-17T23:00:00.000Z",
    "venue": "Toronto",
    "home": {
      "kind": "team",
      "teamId": "ghana"
    },
    "away": {
      "kind": "team",
      "teamId": "panama"
    },
    "officialResult": null
  },
  {
    "id": "m024",
    "number": 24,
    "stage": "group",
    "groupId": "K",
    "roundLabel": "Group K",
    "kickoff": "2026-06-18T02:00:00.000Z",
    "venue": "Mexico City",
    "home": {
      "kind": "team",
      "teamId": "uzbekistan"
    },
    "away": {
      "kind": "team",
      "teamId": "colombia"
    },
    "officialResult": null
  },
  {
    "id": "m025",
    "number": 25,
    "stage": "group",
    "groupId": "A",
    "roundLabel": "Group A",
    "kickoff": "2026-06-18T16:00:00.000Z",
    "venue": "Atlanta",
    "home": {
      "kind": "team",
      "teamId": "czech-republic"
    },
    "away": {
      "kind": "team",
      "teamId": "south-africa"
    },
    "officialResult": null
  },
  {
    "id": "m026",
    "number": 26,
    "stage": "group",
    "groupId": "B",
    "roundLabel": "Group B",
    "kickoff": "2026-06-18T19:00:00.000Z",
    "venue": "Los Angeles (Inglewood)",
    "home": {
      "kind": "team",
      "teamId": "switzerland"
    },
    "away": {
      "kind": "team",
      "teamId": "bosnia-herzegovina"
    },
    "officialResult": null
  },
  {
    "id": "m027",
    "number": 27,
    "stage": "group",
    "groupId": "B",
    "roundLabel": "Group B",
    "kickoff": "2026-06-18T22:00:00.000Z",
    "venue": "Vancouver",
    "home": {
      "kind": "team",
      "teamId": "canada"
    },
    "away": {
      "kind": "team",
      "teamId": "qatar"
    },
    "officialResult": null
  },
  {
    "id": "m028",
    "number": 28,
    "stage": "group",
    "groupId": "A",
    "roundLabel": "Group A",
    "kickoff": "2026-06-19T01:00:00.000Z",
    "venue": "Guadalajara (Zapopan)",
    "home": {
      "kind": "team",
      "teamId": "mexico"
    },
    "away": {
      "kind": "team",
      "teamId": "south-korea"
    },
    "officialResult": null
  },
  {
    "id": "m029",
    "number": 29,
    "stage": "group",
    "groupId": "D",
    "roundLabel": "Group D",
    "kickoff": "2026-06-19T19:00:00.000Z",
    "venue": "Seattle",
    "home": {
      "kind": "team",
      "teamId": "usa"
    },
    "away": {
      "kind": "team",
      "teamId": "australia"
    },
    "officialResult": null
  },
  {
    "id": "m030",
    "number": 30,
    "stage": "group",
    "groupId": "C",
    "roundLabel": "Group C",
    "kickoff": "2026-06-19T22:00:00.000Z",
    "venue": "Boston (Foxborough)",
    "home": {
      "kind": "team",
      "teamId": "scotland"
    },
    "away": {
      "kind": "team",
      "teamId": "morocco"
    },
    "officialResult": null
  },
  {
    "id": "m031",
    "number": 31,
    "stage": "group",
    "groupId": "C",
    "roundLabel": "Group C",
    "kickoff": "2026-06-20T00:30:00.000Z",
    "venue": "Philadelphia",
    "home": {
      "kind": "team",
      "teamId": "brazil"
    },
    "away": {
      "kind": "team",
      "teamId": "haiti"
    },
    "officialResult": null
  },
  {
    "id": "m032",
    "number": 32,
    "stage": "group",
    "groupId": "D",
    "roundLabel": "Group D",
    "kickoff": "2026-06-20T03:00:00.000Z",
    "venue": "San Francisco Bay Area (Santa Clara)",
    "home": {
      "kind": "team",
      "teamId": "turkey"
    },
    "away": {
      "kind": "team",
      "teamId": "paraguay"
    },
    "officialResult": null
  },
  {
    "id": "m033",
    "number": 33,
    "stage": "group",
    "groupId": "F",
    "roundLabel": "Group F",
    "kickoff": "2026-06-20T17:00:00.000Z",
    "venue": "Houston",
    "home": {
      "kind": "team",
      "teamId": "netherlands"
    },
    "away": {
      "kind": "team",
      "teamId": "sweden"
    },
    "officialResult": null
  },
  {
    "id": "m034",
    "number": 34,
    "stage": "group",
    "groupId": "E",
    "roundLabel": "Group E",
    "kickoff": "2026-06-20T20:00:00.000Z",
    "venue": "Toronto",
    "home": {
      "kind": "team",
      "teamId": "germany"
    },
    "away": {
      "kind": "team",
      "teamId": "ivory-coast"
    },
    "officialResult": null
  },
  {
    "id": "m035",
    "number": 35,
    "stage": "group",
    "groupId": "E",
    "roundLabel": "Group E",
    "kickoff": "2026-06-21T00:00:00.000Z",
    "venue": "Kansas City",
    "home": {
      "kind": "team",
      "teamId": "ecuador"
    },
    "away": {
      "kind": "team",
      "teamId": "curacao"
    },
    "officialResult": null
  },
  {
    "id": "m036",
    "number": 36,
    "stage": "group",
    "groupId": "F",
    "roundLabel": "Group F",
    "kickoff": "2026-06-21T04:00:00.000Z",
    "venue": "Monterrey (Guadalupe)",
    "home": {
      "kind": "team",
      "teamId": "tunisia"
    },
    "away": {
      "kind": "team",
      "teamId": "japan"
    },
    "officialResult": null
  },
  {
    "id": "m037",
    "number": 37,
    "stage": "group",
    "groupId": "H",
    "roundLabel": "Group H",
    "kickoff": "2026-06-21T16:00:00.000Z",
    "venue": "Atlanta",
    "home": {
      "kind": "team",
      "teamId": "spain"
    },
    "away": {
      "kind": "team",
      "teamId": "saudi-arabia"
    },
    "officialResult": null
  },
  {
    "id": "m038",
    "number": 38,
    "stage": "group",
    "groupId": "G",
    "roundLabel": "Group G",
    "kickoff": "2026-06-21T19:00:00.000Z",
    "venue": "Los Angeles (Inglewood)",
    "home": {
      "kind": "team",
      "teamId": "belgium"
    },
    "away": {
      "kind": "team",
      "teamId": "iran"
    },
    "officialResult": null
  },
  {
    "id": "m039",
    "number": 39,
    "stage": "group",
    "groupId": "H",
    "roundLabel": "Group H",
    "kickoff": "2026-06-21T22:00:00.000Z",
    "venue": "Miami (Miami Gardens)",
    "home": {
      "kind": "team",
      "teamId": "uruguay"
    },
    "away": {
      "kind": "team",
      "teamId": "cape-verde"
    },
    "officialResult": null
  },
  {
    "id": "m040",
    "number": 40,
    "stage": "group",
    "groupId": "G",
    "roundLabel": "Group G",
    "kickoff": "2026-06-22T01:00:00.000Z",
    "venue": "Vancouver",
    "home": {
      "kind": "team",
      "teamId": "new-zealand"
    },
    "away": {
      "kind": "team",
      "teamId": "egypt"
    },
    "officialResult": null
  },
  {
    "id": "m041",
    "number": 41,
    "stage": "group",
    "groupId": "J",
    "roundLabel": "Group J",
    "kickoff": "2026-06-22T17:00:00.000Z",
    "venue": "Dallas (Arlington)",
    "home": {
      "kind": "team",
      "teamId": "argentina"
    },
    "away": {
      "kind": "team",
      "teamId": "austria"
    },
    "officialResult": null
  },
  {
    "id": "m042",
    "number": 42,
    "stage": "group",
    "groupId": "I",
    "roundLabel": "Group I",
    "kickoff": "2026-06-22T21:00:00.000Z",
    "venue": "Philadelphia",
    "home": {
      "kind": "team",
      "teamId": "france"
    },
    "away": {
      "kind": "team",
      "teamId": "iraq"
    },
    "officialResult": null
  },
  {
    "id": "m043",
    "number": 43,
    "stage": "group",
    "groupId": "I",
    "roundLabel": "Group I",
    "kickoff": "2026-06-23T00:00:00.000Z",
    "venue": "New York/New Jersey (East Rutherford)",
    "home": {
      "kind": "team",
      "teamId": "norway"
    },
    "away": {
      "kind": "team",
      "teamId": "senegal"
    },
    "officialResult": null
  },
  {
    "id": "m044",
    "number": 44,
    "stage": "group",
    "groupId": "J",
    "roundLabel": "Group J",
    "kickoff": "2026-06-23T03:00:00.000Z",
    "venue": "San Francisco Bay Area (Santa Clara)",
    "home": {
      "kind": "team",
      "teamId": "jordan"
    },
    "away": {
      "kind": "team",
      "teamId": "algeria"
    },
    "officialResult": null
  },
  {
    "id": "m045",
    "number": 45,
    "stage": "group",
    "groupId": "K",
    "roundLabel": "Group K",
    "kickoff": "2026-06-23T17:00:00.000Z",
    "venue": "Houston",
    "home": {
      "kind": "team",
      "teamId": "portugal"
    },
    "away": {
      "kind": "team",
      "teamId": "uzbekistan"
    },
    "officialResult": null
  },
  {
    "id": "m046",
    "number": 46,
    "stage": "group",
    "groupId": "L",
    "roundLabel": "Group L",
    "kickoff": "2026-06-23T20:00:00.000Z",
    "venue": "Boston (Foxborough)",
    "home": {
      "kind": "team",
      "teamId": "england"
    },
    "away": {
      "kind": "team",
      "teamId": "ghana"
    },
    "officialResult": null
  },
  {
    "id": "m047",
    "number": 47,
    "stage": "group",
    "groupId": "L",
    "roundLabel": "Group L",
    "kickoff": "2026-06-23T23:00:00.000Z",
    "venue": "Toronto",
    "home": {
      "kind": "team",
      "teamId": "panama"
    },
    "away": {
      "kind": "team",
      "teamId": "croatia"
    },
    "officialResult": null
  },
  {
    "id": "m048",
    "number": 48,
    "stage": "group",
    "groupId": "K",
    "roundLabel": "Group K",
    "kickoff": "2026-06-24T02:00:00.000Z",
    "venue": "Guadalajara (Zapopan)",
    "home": {
      "kind": "team",
      "teamId": "colombia"
    },
    "away": {
      "kind": "team",
      "teamId": "dr-congo"
    },
    "officialResult": null
  },
  {
    "id": "m049",
    "number": 49,
    "stage": "group",
    "groupId": "B",
    "roundLabel": "Group B",
    "kickoff": "2026-06-24T19:00:00.000Z",
    "venue": "Vancouver",
    "home": {
      "kind": "team",
      "teamId": "switzerland"
    },
    "away": {
      "kind": "team",
      "teamId": "canada"
    },
    "officialResult": null
  },
  {
    "id": "m050",
    "number": 50,
    "stage": "group",
    "groupId": "B",
    "roundLabel": "Group B",
    "kickoff": "2026-06-24T19:00:00.000Z",
    "venue": "Seattle",
    "home": {
      "kind": "team",
      "teamId": "bosnia-herzegovina"
    },
    "away": {
      "kind": "team",
      "teamId": "qatar"
    },
    "officialResult": null
  },
  {
    "id": "m051",
    "number": 51,
    "stage": "group",
    "groupId": "C",
    "roundLabel": "Group C",
    "kickoff": "2026-06-24T22:00:00.000Z",
    "venue": "Miami (Miami Gardens)",
    "home": {
      "kind": "team",
      "teamId": "scotland"
    },
    "away": {
      "kind": "team",
      "teamId": "brazil"
    },
    "officialResult": null
  },
  {
    "id": "m052",
    "number": 52,
    "stage": "group",
    "groupId": "C",
    "roundLabel": "Group C",
    "kickoff": "2026-06-24T22:00:00.000Z",
    "venue": "Atlanta",
    "home": {
      "kind": "team",
      "teamId": "morocco"
    },
    "away": {
      "kind": "team",
      "teamId": "haiti"
    },
    "officialResult": null
  },
  {
    "id": "m053",
    "number": 53,
    "stage": "group",
    "groupId": "A",
    "roundLabel": "Group A",
    "kickoff": "2026-06-25T01:00:00.000Z",
    "venue": "Mexico City",
    "home": {
      "kind": "team",
      "teamId": "czech-republic"
    },
    "away": {
      "kind": "team",
      "teamId": "mexico"
    },
    "officialResult": null
  },
  {
    "id": "m054",
    "number": 54,
    "stage": "group",
    "groupId": "A",
    "roundLabel": "Group A",
    "kickoff": "2026-06-25T01:00:00.000Z",
    "venue": "Monterrey (Guadalupe)",
    "home": {
      "kind": "team",
      "teamId": "south-africa"
    },
    "away": {
      "kind": "team",
      "teamId": "south-korea"
    },
    "officialResult": null
  },
  {
    "id": "m055",
    "number": 55,
    "stage": "group",
    "groupId": "E",
    "roundLabel": "Group E",
    "kickoff": "2026-06-25T20:00:00.000Z",
    "venue": "Philadelphia",
    "home": {
      "kind": "team",
      "teamId": "curacao"
    },
    "away": {
      "kind": "team",
      "teamId": "ivory-coast"
    },
    "officialResult": null
  },
  {
    "id": "m056",
    "number": 56,
    "stage": "group",
    "groupId": "E",
    "roundLabel": "Group E",
    "kickoff": "2026-06-25T20:00:00.000Z",
    "venue": "New York/New Jersey (East Rutherford)",
    "home": {
      "kind": "team",
      "teamId": "ecuador"
    },
    "away": {
      "kind": "team",
      "teamId": "germany"
    },
    "officialResult": null
  },
  {
    "id": "m057",
    "number": 57,
    "stage": "group",
    "groupId": "F",
    "roundLabel": "Group F",
    "kickoff": "2026-06-25T23:00:00.000Z",
    "venue": "Dallas (Arlington)",
    "home": {
      "kind": "team",
      "teamId": "japan"
    },
    "away": {
      "kind": "team",
      "teamId": "sweden"
    },
    "officialResult": null
  },
  {
    "id": "m058",
    "number": 58,
    "stage": "group",
    "groupId": "F",
    "roundLabel": "Group F",
    "kickoff": "2026-06-25T23:00:00.000Z",
    "venue": "Kansas City",
    "home": {
      "kind": "team",
      "teamId": "tunisia"
    },
    "away": {
      "kind": "team",
      "teamId": "netherlands"
    },
    "officialResult": null
  },
  {
    "id": "m059",
    "number": 59,
    "stage": "group",
    "groupId": "D",
    "roundLabel": "Group D",
    "kickoff": "2026-06-26T02:00:00.000Z",
    "venue": "Los Angeles (Inglewood)",
    "home": {
      "kind": "team",
      "teamId": "turkey"
    },
    "away": {
      "kind": "team",
      "teamId": "usa"
    },
    "officialResult": null
  },
  {
    "id": "m060",
    "number": 60,
    "stage": "group",
    "groupId": "D",
    "roundLabel": "Group D",
    "kickoff": "2026-06-26T02:00:00.000Z",
    "venue": "San Francisco Bay Area (Santa Clara)",
    "home": {
      "kind": "team",
      "teamId": "paraguay"
    },
    "away": {
      "kind": "team",
      "teamId": "australia"
    },
    "officialResult": null
  },
  {
    "id": "m061",
    "number": 61,
    "stage": "group",
    "groupId": "I",
    "roundLabel": "Group I",
    "kickoff": "2026-06-26T19:00:00.000Z",
    "venue": "Boston (Foxborough)",
    "home": {
      "kind": "team",
      "teamId": "norway"
    },
    "away": {
      "kind": "team",
      "teamId": "france"
    },
    "officialResult": null
  },
  {
    "id": "m062",
    "number": 62,
    "stage": "group",
    "groupId": "I",
    "roundLabel": "Group I",
    "kickoff": "2026-06-26T19:00:00.000Z",
    "venue": "Toronto",
    "home": {
      "kind": "team",
      "teamId": "senegal"
    },
    "away": {
      "kind": "team",
      "teamId": "iraq"
    },
    "officialResult": null
  },
  {
    "id": "m063",
    "number": 63,
    "stage": "group",
    "groupId": "H",
    "roundLabel": "Group H",
    "kickoff": "2026-06-27T00:00:00.000Z",
    "venue": "Houston",
    "home": {
      "kind": "team",
      "teamId": "cape-verde"
    },
    "away": {
      "kind": "team",
      "teamId": "saudi-arabia"
    },
    "officialResult": null
  },
  {
    "id": "m064",
    "number": 64,
    "stage": "group",
    "groupId": "H",
    "roundLabel": "Group H",
    "kickoff": "2026-06-27T00:00:00.000Z",
    "venue": "Guadalajara (Zapopan)",
    "home": {
      "kind": "team",
      "teamId": "uruguay"
    },
    "away": {
      "kind": "team",
      "teamId": "spain"
    },
    "officialResult": null
  },
  {
    "id": "m065",
    "number": 65,
    "stage": "group",
    "groupId": "G",
    "roundLabel": "Group G",
    "kickoff": "2026-06-27T03:00:00.000Z",
    "venue": "Seattle",
    "home": {
      "kind": "team",
      "teamId": "egypt"
    },
    "away": {
      "kind": "team",
      "teamId": "iran"
    },
    "officialResult": null
  },
  {
    "id": "m066",
    "number": 66,
    "stage": "group",
    "groupId": "G",
    "roundLabel": "Group G",
    "kickoff": "2026-06-27T03:00:00.000Z",
    "venue": "Vancouver",
    "home": {
      "kind": "team",
      "teamId": "new-zealand"
    },
    "away": {
      "kind": "team",
      "teamId": "belgium"
    },
    "officialResult": null
  },
  {
    "id": "m067",
    "number": 67,
    "stage": "group",
    "groupId": "L",
    "roundLabel": "Group L",
    "kickoff": "2026-06-27T21:00:00.000Z",
    "venue": "New York/New Jersey (East Rutherford)",
    "home": {
      "kind": "team",
      "teamId": "panama"
    },
    "away": {
      "kind": "team",
      "teamId": "england"
    },
    "officialResult": null
  },
  {
    "id": "m068",
    "number": 68,
    "stage": "group",
    "groupId": "L",
    "roundLabel": "Group L",
    "kickoff": "2026-06-27T21:00:00.000Z",
    "venue": "Philadelphia",
    "home": {
      "kind": "team",
      "teamId": "croatia"
    },
    "away": {
      "kind": "team",
      "teamId": "ghana"
    },
    "officialResult": null
  },
  {
    "id": "m069",
    "number": 69,
    "stage": "group",
    "groupId": "K",
    "roundLabel": "Group K",
    "kickoff": "2026-06-27T23:30:00.000Z",
    "venue": "Miami (Miami Gardens)",
    "home": {
      "kind": "team",
      "teamId": "colombia"
    },
    "away": {
      "kind": "team",
      "teamId": "portugal"
    },
    "officialResult": null
  },
  {
    "id": "m070",
    "number": 70,
    "stage": "group",
    "groupId": "K",
    "roundLabel": "Group K",
    "kickoff": "2026-06-27T23:30:00.000Z",
    "venue": "Atlanta",
    "home": {
      "kind": "team",
      "teamId": "dr-congo"
    },
    "away": {
      "kind": "team",
      "teamId": "uzbekistan"
    },
    "officialResult": null
  },
  {
    "id": "m071",
    "number": 71,
    "stage": "group",
    "groupId": "J",
    "roundLabel": "Group J",
    "kickoff": "2026-06-28T02:00:00.000Z",
    "venue": "Kansas City",
    "home": {
      "kind": "team",
      "teamId": "algeria"
    },
    "away": {
      "kind": "team",
      "teamId": "austria"
    },
    "officialResult": null
  },
  {
    "id": "m072",
    "number": 72,
    "stage": "group",
    "groupId": "J",
    "roundLabel": "Group J",
    "kickoff": "2026-06-28T02:00:00.000Z",
    "venue": "Dallas (Arlington)",
    "home": {
      "kind": "team",
      "teamId": "jordan"
    },
    "away": {
      "kind": "team",
      "teamId": "argentina"
    },
    "officialResult": null
  },
  {
    "id": "m073",
    "number": 73,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-06-28T19:00:00.000Z",
    "venue": "Los Angeles (Inglewood)",
    "home": {
      "kind": "placeholder",
      "label": "2A"
    },
    "away": {
      "kind": "placeholder",
      "label": "2B"
    },
    "officialResult": null
  },
  {
    "id": "m074",
    "number": 74,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-06-29T20:30:00.000Z",
    "venue": "Boston (Foxborough)",
    "home": {
      "kind": "placeholder",
      "label": "1E"
    },
    "away": {
      "kind": "placeholder",
      "label": "3A/B/C/D/F"
    },
    "officialResult": null
  },
  {
    "id": "m075",
    "number": 75,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-06-30T01:00:00.000Z",
    "venue": "Monterrey (Guadalupe)",
    "home": {
      "kind": "placeholder",
      "label": "1F"
    },
    "away": {
      "kind": "placeholder",
      "label": "2C"
    },
    "officialResult": null
  },
  {
    "id": "m076",
    "number": 76,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-06-29T17:00:00.000Z",
    "venue": "Houston",
    "home": {
      "kind": "placeholder",
      "label": "1C"
    },
    "away": {
      "kind": "placeholder",
      "label": "2F"
    },
    "officialResult": null
  },
  {
    "id": "m077",
    "number": 77,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-06-30T21:00:00.000Z",
    "venue": "New York/New Jersey (East Rutherford)",
    "home": {
      "kind": "placeholder",
      "label": "1I"
    },
    "away": {
      "kind": "placeholder",
      "label": "3C/D/F/G/H"
    },
    "officialResult": null
  },
  {
    "id": "m078",
    "number": 78,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-06-30T17:00:00.000Z",
    "venue": "Dallas (Arlington)",
    "home": {
      "kind": "placeholder",
      "label": "2E"
    },
    "away": {
      "kind": "placeholder",
      "label": "2I"
    },
    "officialResult": null
  },
  {
    "id": "m079",
    "number": 79,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-01T01:00:00.000Z",
    "venue": "Mexico City",
    "home": {
      "kind": "placeholder",
      "label": "1A"
    },
    "away": {
      "kind": "placeholder",
      "label": "3C/E/F/H/I"
    },
    "officialResult": null
  },
  {
    "id": "m080",
    "number": 80,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-01T16:00:00.000Z",
    "venue": "Atlanta",
    "home": {
      "kind": "placeholder",
      "label": "1L"
    },
    "away": {
      "kind": "placeholder",
      "label": "3E/H/I/J/K"
    },
    "officialResult": null
  },
  {
    "id": "m081",
    "number": 81,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-02T00:00:00.000Z",
    "venue": "San Francisco Bay Area (Santa Clara)",
    "home": {
      "kind": "placeholder",
      "label": "1D"
    },
    "away": {
      "kind": "placeholder",
      "label": "3B/E/F/I/J"
    },
    "officialResult": null
  },
  {
    "id": "m082",
    "number": 82,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-01T20:00:00.000Z",
    "venue": "Seattle",
    "home": {
      "kind": "placeholder",
      "label": "1G"
    },
    "away": {
      "kind": "placeholder",
      "label": "3A/E/H/I/J"
    },
    "officialResult": null
  },
  {
    "id": "m083",
    "number": 83,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-02T23:00:00.000Z",
    "venue": "Toronto",
    "home": {
      "kind": "placeholder",
      "label": "2K"
    },
    "away": {
      "kind": "placeholder",
      "label": "2L"
    },
    "officialResult": null
  },
  {
    "id": "m084",
    "number": 84,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-02T19:00:00.000Z",
    "venue": "Los Angeles (Inglewood)",
    "home": {
      "kind": "placeholder",
      "label": "1H"
    },
    "away": {
      "kind": "placeholder",
      "label": "2J"
    },
    "officialResult": null
  },
  {
    "id": "m085",
    "number": 85,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-03T03:00:00.000Z",
    "venue": "Vancouver",
    "home": {
      "kind": "placeholder",
      "label": "1B"
    },
    "away": {
      "kind": "placeholder",
      "label": "3E/F/G/I/J"
    },
    "officialResult": null
  },
  {
    "id": "m086",
    "number": 86,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-03T22:00:00.000Z",
    "venue": "Miami (Miami Gardens)",
    "home": {
      "kind": "placeholder",
      "label": "1J"
    },
    "away": {
      "kind": "placeholder",
      "label": "2H"
    },
    "officialResult": null
  },
  {
    "id": "m087",
    "number": 87,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-04T01:30:00.000Z",
    "venue": "Kansas City",
    "home": {
      "kind": "placeholder",
      "label": "1K"
    },
    "away": {
      "kind": "placeholder",
      "label": "3D/E/I/J/L"
    },
    "officialResult": null
  },
  {
    "id": "m088",
    "number": 88,
    "stage": "round32",
    "groupId": null,
    "roundLabel": "Round of 32",
    "kickoff": "2026-07-03T18:00:00.000Z",
    "venue": "Dallas (Arlington)",
    "home": {
      "kind": "placeholder",
      "label": "2D"
    },
    "away": {
      "kind": "placeholder",
      "label": "2G"
    },
    "officialResult": null
  },
  {
    "id": "m089",
    "number": 89,
    "stage": "round16",
    "groupId": null,
    "roundLabel": "Round of 16",
    "kickoff": "2026-07-04T21:00:00.000Z",
    "venue": "Philadelphia",
    "home": {
      "kind": "placeholder",
      "label": "W74"
    },
    "away": {
      "kind": "placeholder",
      "label": "W77"
    },
    "officialResult": null
  },
  {
    "id": "m090",
    "number": 90,
    "stage": "round16",
    "groupId": null,
    "roundLabel": "Round of 16",
    "kickoff": "2026-07-04T17:00:00.000Z",
    "venue": "Houston",
    "home": {
      "kind": "placeholder",
      "label": "W73"
    },
    "away": {
      "kind": "placeholder",
      "label": "W75"
    },
    "officialResult": null
  },
  {
    "id": "m091",
    "number": 91,
    "stage": "round16",
    "groupId": null,
    "roundLabel": "Round of 16",
    "kickoff": "2026-07-05T20:00:00.000Z",
    "venue": "New York/New Jersey (East Rutherford)",
    "home": {
      "kind": "placeholder",
      "label": "W76"
    },
    "away": {
      "kind": "placeholder",
      "label": "W78"
    },
    "officialResult": null
  },
  {
    "id": "m092",
    "number": 92,
    "stage": "round16",
    "groupId": null,
    "roundLabel": "Round of 16",
    "kickoff": "2026-07-06T00:00:00.000Z",
    "venue": "Mexico City",
    "home": {
      "kind": "placeholder",
      "label": "W79"
    },
    "away": {
      "kind": "placeholder",
      "label": "W80"
    },
    "officialResult": null
  },
  {
    "id": "m093",
    "number": 93,
    "stage": "round16",
    "groupId": null,
    "roundLabel": "Round of 16",
    "kickoff": "2026-07-06T19:00:00.000Z",
    "venue": "Dallas (Arlington)",
    "home": {
      "kind": "placeholder",
      "label": "W83"
    },
    "away": {
      "kind": "placeholder",
      "label": "W84"
    },
    "officialResult": null
  },
  {
    "id": "m094",
    "number": 94,
    "stage": "round16",
    "groupId": null,
    "roundLabel": "Round of 16",
    "kickoff": "2026-07-07T00:00:00.000Z",
    "venue": "Seattle",
    "home": {
      "kind": "placeholder",
      "label": "W81"
    },
    "away": {
      "kind": "placeholder",
      "label": "W82"
    },
    "officialResult": null
  },
  {
    "id": "m095",
    "number": 95,
    "stage": "round16",
    "groupId": null,
    "roundLabel": "Round of 16",
    "kickoff": "2026-07-07T16:00:00.000Z",
    "venue": "Atlanta",
    "home": {
      "kind": "placeholder",
      "label": "W86"
    },
    "away": {
      "kind": "placeholder",
      "label": "W88"
    },
    "officialResult": null
  },
  {
    "id": "m096",
    "number": 96,
    "stage": "round16",
    "groupId": null,
    "roundLabel": "Round of 16",
    "kickoff": "2026-07-07T20:00:00.000Z",
    "venue": "Vancouver",
    "home": {
      "kind": "placeholder",
      "label": "W85"
    },
    "away": {
      "kind": "placeholder",
      "label": "W87"
    },
    "officialResult": null
  },
  {
    "id": "m097",
    "number": 97,
    "stage": "quarter",
    "groupId": null,
    "roundLabel": "Quarter-final",
    "kickoff": "2026-07-09T20:00:00.000Z",
    "venue": "Boston (Foxborough)",
    "home": {
      "kind": "placeholder",
      "label": "W89"
    },
    "away": {
      "kind": "placeholder",
      "label": "W90"
    },
    "officialResult": null
  },
  {
    "id": "m098",
    "number": 98,
    "stage": "quarter",
    "groupId": null,
    "roundLabel": "Quarter-final",
    "kickoff": "2026-07-10T19:00:00.000Z",
    "venue": "Los Angeles (Inglewood)",
    "home": {
      "kind": "placeholder",
      "label": "W93"
    },
    "away": {
      "kind": "placeholder",
      "label": "W94"
    },
    "officialResult": null
  },
  {
    "id": "m099",
    "number": 99,
    "stage": "quarter",
    "groupId": null,
    "roundLabel": "Quarter-final",
    "kickoff": "2026-07-11T21:00:00.000Z",
    "venue": "Miami (Miami Gardens)",
    "home": {
      "kind": "placeholder",
      "label": "W91"
    },
    "away": {
      "kind": "placeholder",
      "label": "W92"
    },
    "officialResult": null
  },
  {
    "id": "m100",
    "number": 100,
    "stage": "quarter",
    "groupId": null,
    "roundLabel": "Quarter-final",
    "kickoff": "2026-07-12T01:00:00.000Z",
    "venue": "Kansas City",
    "home": {
      "kind": "placeholder",
      "label": "W95"
    },
    "away": {
      "kind": "placeholder",
      "label": "W96"
    },
    "officialResult": null
  },
  {
    "id": "m101",
    "number": 101,
    "stage": "semi",
    "groupId": null,
    "roundLabel": "Semi-final",
    "kickoff": "2026-07-14T19:00:00.000Z",
    "venue": "Dallas (Arlington)",
    "home": {
      "kind": "placeholder",
      "label": "W97"
    },
    "away": {
      "kind": "placeholder",
      "label": "W98"
    },
    "officialResult": null
  },
  {
    "id": "m102",
    "number": 102,
    "stage": "semi",
    "groupId": null,
    "roundLabel": "Semi-final",
    "kickoff": "2026-07-15T19:00:00.000Z",
    "venue": "Atlanta",
    "home": {
      "kind": "placeholder",
      "label": "W99"
    },
    "away": {
      "kind": "placeholder",
      "label": "W100"
    },
    "officialResult": null
  },
  {
    "id": "m103",
    "number": 103,
    "stage": "third",
    "groupId": null,
    "roundLabel": "Match for third place",
    "kickoff": "2026-07-18T21:00:00.000Z",
    "venue": "Miami (Miami Gardens)",
    "home": {
      "kind": "placeholder",
      "label": "L101"
    },
    "away": {
      "kind": "placeholder",
      "label": "L102"
    },
    "officialResult": null
  },
  {
    "id": "m104",
    "number": 104,
    "stage": "final",
    "groupId": null,
    "roundLabel": "Final",
    "kickoff": "2026-07-19T19:00:00.000Z",
    "venue": "New York/New Jersey (East Rutherford)",
    "home": {
      "kind": "placeholder",
      "label": "W101"
    },
    "away": {
      "kind": "placeholder",
      "label": "W102"
    },
    "officialResult": null
  }
];
